apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ENROLL_DOMAIN}}
  name: enroll-o{{ORDERER_INDEX}}-{{ORDERER}}
spec:
  template:
    metadata:
      labels:
       app: hyperledger
       role: {{ORDERER}}
       org: {{ENROLL_DOMAIN}}
       name: enroll-o{{ORDERER_INDEX}}-{{ORDERER}}
    spec:
     restartPolicy: "Never"
     containers:
       - name: enroll-o{{ORDERER_INDEX}}-{{ORDERER}}
         image: hyperledger/fabric-ca:{{FABRIC_CA_TAG}}
         env:
          - name: ORDERERORG
            value: {{ORDERER}}
          - name: FABRIC_CA_CLIENT_TLS_CERTFILES
            value: /data/ica-{{ORDERER}}-ca-chain.pem
          - name: ORDERER_HOME
            value: /etc/hyperledger/orderer
         command: ["sh"]
         args:  ["-c", "/scripts/enroll-orderer.sh {{ORDERER_INDEX}} 2>&1;"]
         volumeMounts:
          - mountPath: /scripts
            name: rca-scripts
          - mountPath: /data
            name: rca-data
     volumes:
       - name: rca-scripts
         nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-scripts/
       - name: rca-data
         nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-data/
