kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encryption
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext4
  encrypted: "true"
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true