
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{DOMAIN}}
  name: signchannelconfig
spec:
  backoffLimit: 1
  template:
    metadata:
      name: signchannelconfig
    spec:
      restartPolicy: "Never"
      containers:
      - name: signchannelconfig
        image: hyperledger/fabric-tools:1.4.1
        command: 
        - /bin/sh
        - -c
        - |
          set -xe
          cd /shared;
          peer channel signconfigtx -f "${UPDATED_ENVELOPE_PB}"
          RETURN_CODE=$?
          if [ $RETURN_CODE -eq "0" ]
          then
            echo 'Success signconfigtx'
          else
            echo 'Failed signconfigtx'
          fi
        env:
        - name: UPDATED_ENVELOPE_PB
          value: config-update-in-envelope.pb
        - name: CORE_PEER_LOCALMSPID
          value: {{ORGMSP}}
        - name: CORE_PEER_LOCALMSPNAME
          value: {{ORGMSP}}
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /shared/crypto-config/peerOrganizations/{{ORGDOMAIN}}/peers/peer0.{{ORGDOMAIN}}/tls/ca.crt
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/crypto-config/peerOrganizations/{{ORGDOMAIN}}/users/admin/msp/
        - name: CORE_PEER_ADDRESS
          value: peer0-{{ORGNAME}}.{{ORGDOMAIN}}:7051
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_LOGGING_LEVEL
          value: DEBUG
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_NETWORKID
          value: cli
        volumeMounts:
          - name: crypto-config
            mountPath: /shared
      volumes:
      - name: crypto-config
        nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-data
