---
apiVersion: v1
kind: Service
metadata:
  namespace: {{DOMAIN}}
  name: explorer-db
spec:
  selector:
    app: explorer-db
    tier: {{DOMAIN}}
  type: NodePort
  ports:
  - name: explorer-db-port
    protocol: TCP
    port: 5432
    targetPort: 5432
