---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  namespace: default
spec:
  storageClassName: azurefile
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
