---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{ORDERER_DOMAIN}}
  name: orderer{{ORDERER_INDEX}}-{{ORDERER}}
spec:
  serviceName: orderer{{ORDERER_INDEX}}-{{ORDERER}}
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      role: orderer
      org: {{ORDERER_DOMAIN}}
      orderer-id: orderer{{ORDERER_INDEX}}-{{ORDERER}}
  template:
    metadata:
      labels:
        app: hyperledger
        role: orderer
        org: {{ORDERER_DOMAIN}}
        orderer-id: orderer{{ORDERER_INDEX}}-{{ORDERER}}
    spec:
      containers:
      - name: orderer{{ORDERER_INDEX}}-orderer-akc
        image: hyperledger/fabric-orderer:1.4.1
        # resources:
        #   requests:
        #     memory: "150Mi"
        #     cpu: "50m"
        #   limits:
        #     memory: "3000Mi"
        #     cpu: "2"
        command: ["sh", "-c", "orderer"]
        env:
        - name: FABRIC_LOGGING_SPEC
          #value: info
          value: DEBUG
        - name: ORDERER_CFG_PATH
          value: /shared/
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /var/ledger/orderer{{ORDERER_INDEX}}
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /shared/crypto-config/ordererOrganizations/{{ORDERER_DOMAIN}}/orderers/orderer{{ORDERER_INDEX}}-{{ORDERER}}.{{ORDERER_DOMAIN}}/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: ordererMSP
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /shared/genesis.block
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "true"
        - name: ORDERER_GENERAL_TLS_PRIVATEKEY
          value: /shared/crypto-config/ordererOrganizations/{{ORDERER_DOMAIN}}/orderers/orderer{{ORDERER_INDEX}}-{{ORDERER}}.{{ORDERER_DOMAIN}}/tls/server.key
        - name: ORDERER_GENERAL_TLS_CERTIFICATE
          value: /shared/crypto-config/ordererOrganizations/{{ORDERER_DOMAIN}}/orderers/orderer{{ORDERER_INDEX}}-{{ORDERER}}.{{ORDERER_DOMAIN}}/tls/server.crt
        # THIS IS BROKEN: * 'General.TLS.RootCAs': source data must be an array or slice, got string
        - name: ORDERER_GENERAL_TLS_ROOTCAS
          value: /shared/crypto-config/ordererOrganizations/{{ORDERER_DOMAIN}}/orderers/orderer{{ORDERER_INDEX}}-{{ORDERER}}.{{ORDERER_DOMAIN}}/tls/tlsca.{{ORDERER_DOMAIN}}-cert.pem
        - name: GODEBUG
          value: netdns=go
        - name: ORDERER_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:10443
        - name: ORDERER_METRICS_PROVIDER
          value: prometheus
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
        ports:
        - containerPort: 7050
        - containerPort: 10443
        volumeMounts:
          - name: crypto-config
            mountPath: /shared
          - name: orderer{{ORDERER_INDEX}}-{{ORDERER_DOMAIN}}-pvc-akc
            mountPath: /var/ledger
            mountPath: /var/ledger/orderer{{ORDERER_INDEX}}
      volumes:
      - name: crypto-config
        nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-data/
  volumeClaimTemplates:
  - metadata:
      name: orderer{{ORDERER_INDEX}}-{{ORDERER_DOMAIN}}-pvc-akc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{STORE_CLASS}}
      resources:
        requests:
          storage: 10Gi
