---
apiVersion: v1
kind: Service
metadata:
  name: orderer{{ORDERER_INDEX}}-{{ORDERER}}-nlb
  namespace: {{ORDERER_DOMAIN}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: hyperledger
    role: orderer
    orderer-id: orderer{{ORDERER_INDEX}}-{{ORDERER}}
    org: {{ORDERER_DOMAIN}}
  ports:
  - name: listen-endpoint
    protocol: TCP
    port: 7050
    targetPort: 7050
  type: LoadBalancer
