---
  apiVersion: apps/v1
  kind: StatefulSet
  metadata:
    namespace: {{PEER_DOMAIN}}
    name: couchdb{{PEER_INDEX}}-{{PEER_ORG}}
  spec:
    serviceName: couchdb{{PEER_INDEX}}
    replicas: 1
    selector:
      matchLabels:
        app: hyperledger
        role: couchdb
        couchdb-id: couchdb{{PEER_INDEX}}-{{PEER_ORG}}
        org: {{PEER_DOMAIN}}
        type: stateful
    template:
      metadata:
        labels:
          app: hyperledger
          role: couchdb
          couchdb-id: couchdb{{PEER_INDEX}}-{{PEER_ORG}}
          org: {{PEER_DOMAIN}}
          type: stateful
      spec:
        containers:
        - name: couchdb
          image: couchdb:{{COUCHDB_TAG}}
          ports:
            - containerPort: 5984
          # resources:
          #   requests:
          #     # memory: "3000Mi"
          #     # cpu: "2000m"
          #     memory: "150Mi"
          #     cpu: "100m"
          volumeMounts:
          - name: couch{{PEER_INDEX}}-pvc-{{PEER_DOMAIN}}
            mountPath: /opt/couchdb/data
          env:
          - name: COUCHDB_USER
            value: admin
          - name: COUCHDB_PASSWORD
            value: -pbkdf2-847043acc65626c8eb98da6d78682fbc493a1787,f7b1a3e4b624f4f0bbfe87e96841eda0,10
          - name: COUCHDB_SECRET
            value: 0123456789abcdef0123456789abcdef
          - name: NODENAME
            value: couchdb{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}
    volumeClaimTemplates:
    - metadata:
        name: couch{{PEER_INDEX}}-pvc-{{PEER_DOMAIN}}
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{STORAGE_CLASS}}
        resources:
          requests:
            storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: {{PEER_DOMAIN}}
  name: peer{{PEER_INDEX}}-{{PEER_ORG}}
spec:
  serviceName: peer{{PEER_INDEX}}-{{PEER_ORG}}
  replicas: 1
  selector:
    matchLabels:
      app: hyperledger
      role: peer
      peer-id: peer{{PEER_INDEX}}-{{PEER_ORG}}
      org: {{PEER_DOMAIN}}
      type: stateful
  template:
    metadata:
      labels:
        app: hyperledger
        role: peer
        peer-id: peer{{PEER_INDEX}}-{{PEER_ORG}}
        org: {{PEER_DOMAIN}}
        type: stateful
    spec:
      containers:
      - name: peer{{PEER_INDEX}}-{{PEER_ORG}}
        image: hyperledger/fabric-peer:{{FABRIC_TAG}}
        # resources:
        #   requests:
        #     # memory: "3000Mi"
        #     memory: "300Mi"
        #     cpu: "200m"
        command: ["sh", "-c", "peer node start"]
        env:
        - name: CORE_CHAINCODE_BUILDER
          value: hyperledger/fabric-ccenv:{{FABRIC_TAG}}
        - name: CORE_PEER_ID
          value: peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}
        - name: CORE_PEER_GOSSIP_BOOTSTRAP
          value: peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}:7051
        - name: CORE_PEER_GOSSIP_EXTERNALENDPOINT
          value: peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}:7051
        - name: CORE_PEER_GOSSIP_USELEADERELECTION
          value: "false"
        - name: CORE_PEER_GOSSIP_ORGLEADER
          value: "true"
        - name: CORE_PEER_COMMITTER_ENABLED
          value: "true"
        - name: CORE_PEER_PROFILE_ENABLED
          value: "true"
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: CORE_PEER_LOCALMSPID
          value: {{PEER_ORG}}MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /shared/peers/peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}/msp/
          #- name: FABRIC_LOGGING_SPEC
          #value: info
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_CERT_FILE
          value: /shared/peers/peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /shared/peers/peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /shared/peers/peer{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}/tls/tlscacerts/tls-ica-{{PEER_ORG}}-{{PEER_DOMAIN}}-7054.pem
        - name: CORE_LEDGER_STATE_STATEDATABASE
          value: CouchDB
        - name: FABRIC_CFG_PATH
          value: /etc/hyperledger/fabric/
        - name: GODEBUG
          value: "netdns=go"
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
          value: couchdb{{PEER_INDEX}}-{{PEER_ORG}}.{{PEER_DOMAIN}}:5984
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME
          value: admin
        - name: CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
          value: password
        - name: CORE_PEER_ADDRESSAUTODETECT
          value: "true"
        - name: CORE_OPERATIONS_LISTENADDRESS
          value: 0.0.0.0:9443
        - name: CORE_METRICS_PROVIDER
          value: prometheus
        # Allow more time for chaincode container to build on install.
        - name: CORE_CHAINCODE_EXECUTETIMEOUT
          value: 300s
        - name: FABRIC_LOGGING_SPEC
          value: INFO
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        ports:
        - containerPort: 7051
        - containerPort: 7052
        - containerPort: 7053
        - containerPort: 9443

        volumeMounts:
          - name: crypto-config
            mountPath: /shared
          - name: builders-config
            mountPath: /etc/hyperledger/fabric/core.yaml
            subPath: core.yaml
          - name: external-builder
            mountPath: /builders/external/bin
          - name: dockersocket
            mountPath: /host/var/run/docker.sock
          - name: peer{{PEER_INDEX}}-pvc-{{PEER_DOMAIN}}
            mountPath: /var/hyperledger/production
      volumes:
      - name: crypto-config
        nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-data/crypto-config/{{PEER_ORG}}.{{PEER_DOMAIN}}
      - name: builders-config
        configMap:
          name: builders-config
          items:
            - key: core.yaml
              path: core.yaml
      - name: external-builder
        nfs:
          server: {{EFS_SERVER}}
          path: {{PVS_PATH}}/{{EFS_PATH}}/{{EFS_EXTEND}}/akc-ca-scripts/buildpack/bin/
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
  volumeClaimTemplates:
  - metadata:
      name: peer{{PEER_INDEX}}-pvc-{{PEER_DOMAIN}}
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{STORAGE_CLASS}}
      resources:
        requests:
          storage: 5Gi

