---
apiVersion: v1
kind: Service
metadata:
  namespace: {{PEER_DOMAIN}}
  name: chaincode-{{CHAINCODE_NAME}}-{{PEER_NAME}}
spec:
  selector:
    app: chaincode-{{CHAINCODE_NAME}}-{{PEER_NAME}}
    tier: {{PEER_DOMAIN}}
  type: NodePort
  ports:
  - name: chaincode-{{CHAINCODE_NAME}}-{{PEER_NAME}}-port
    protocol: TCP
    port: 7052
    targetPort: 7052
