---
apiVersion: v1
kind: Service
metadata:
  namespace: {{DOMAIN}}
  name: explorer
spec:
  selector:
    app: explorer
    tier: {{DOMAIN}}
  type: NodePort
  ports:
  - name: explorer-port
    protocol: TCP
    port: 8008
    targetPort: 8080
