---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ORG_DOMAIN}}
  name: admin-v2-{{ORG_NAME}}
spec:
  selector:
    app: admin-v2-{{ORG_NAME}}
    tier: {{ORG_DOMAIN}}
  type: NodePort
  ports:
  - name: admin-port
    protocol: TCP
    port: 4001
    targetPort: 4001
