---
apiVersion: v1
kind: Service
metadata:
  name: {{RCA_NAME}}-nlb
  namespace: {{ORG}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: hyperledger
    role: ca
    org: {{ORG}}
    name: {{RCA_NAME}}
  ports:
  - name: endpoint
    protocol: TCP
    port: 7054
    targetPort: 7054
  type: LoadBalancer