---
apiVersion: v1
kind: Service
metadata:
  name: peer{{PEER_INDEX}}-{{PEER_ORG}}-nlb
  namespace: {{PEER_DOMAIN}}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  selector:
    app: hyperledger
    role: peer
    peer-id: peer{{PEER_INDEX}}-{{PEER_ORG}}
    org: {{PEER_DOMAIN}}
    type: stateful
  ports:
  - name: external-listen-endpoint
    protocol: TCP
    port: 7051
    targetPort: 7051

  - name: chaincode-listen
    protocol: TCP
    port: 7052
    targetPort: 7052

  - name: event-listen
    protocol: TCP
    port: 7053
    targetPort: 7053
  type: LoadBalancer
