apiVersion: v1
kind: PersistentVolume
metadata:
  name: mamba-nfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: mambanfs.file.core.windows.net
    path: /mambanfs/mamba-nfs
