apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mamba-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ''
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
