# A headless service to create DNS records
---
apiVersion: v1
kind: Service
metadata:
  name: broker
  namespace: {{KAFKA_NAMESPACE}}
spec:
  ports:
  - port: 9092
  clusterIP: None
  selector:
    app: kafka
