apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: {{KAFKA_NAMESPACE}}
spec:
  serviceName: "broker"
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: broker
        image: hyperledger/fabric-kafka
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "102760448"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "102760448"
        - name: KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE
          value: "false"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          # value: "3"
          value: "1"
        - name: KAFKA_MIN_INSYNC_REPLICAS
          # value: "2"
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo-0.zoo:2181,zoo-1.zoo:2181,zoo-2.zoo:2181
        - name: KAFKA_PORT
          value: "9092"
        - name: GODEBUG
          value: netdns=go
        - name: KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS
          value: "30000"
        - name: KAFKA_LOG_DIRS
          value: /opt/kafka/data
        volumeMounts:
        - name: datadir
          mountPath: /opt/kafka/data
          subPath: kafka
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 5Gi
