---
apiVersion: v1
kind: Service
metadata:
  namespace: {{DOMAIN}}
  name: grafana
spec:
  selector:
    app: hyperledger
    role: grafana
    type: stateful
  type: NodePort
  ports:
  - name: externale-listen-endpoint
    protocol: TCP
    port: 3000
    targetPort: 3000