  
---
apiVersion: v1
kind: Service
metadata:
  namespace: {{ORDERER_DOMAIN}}
  name: admin-v1
spec:
  selector:
    app: admin-v1
    tier: {{ORDERER_DOMAIN}}
  type: NodePort
  ports:
  - name: admin-port
    protocol: TCP
    port: 4001
    targetPort: 4001
    # nodePort: 32330